name: Release and Publish SDKs

on:
  pull_request:
    types:
        - closed
    branches:
      - SDK-Release-Test
      #- master #TODO: Uncomment this when we are ready to merge to master

jobs:
  Filter-Branch:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'SDK')
    steps:
      - run: echo "SDK label found. Continuing..."
  Check-PR-Labels:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      RELEASE_TYPE: ${{ steps.set_labels.outputs.RELEASE_TYPE }}
      V1: ${{ steps.set_labels.outputs.V1 }}
      V2: ${{ steps.set_labels.outputs.V2 }}
      DIRECTORYINSIGHTS: ${{ steps.set_labels.outputs.DIRECTORYINSIGHTS }}
    steps:
      - name: Set Environment Variables from PR Labels
        id: set_labels
        shell: pwsh
        run: |
          # Fetch and natively parse the JSON list of labels from the PR
          $jsonResponse = curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" `
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"
          $PR_LABEL_LIST = ($jsonResponse | ConvertFrom-Json).name
          Write-Host "Found labels on PR: $($PR_LABEL_LIST -join ', ')"

          # --- Set Release Type Environment Variable using a loop ---
          $validReleaseTypes = @('major', 'minor', 'patch', 'manual')
          $validSdkTypes = @('v1', 'v2', 'DirectoryInsights')
          $foundReleaseType = ''
          $typeCount = 0
          $sdkTypeCount = 0

          # Loop through the labels found on the PR
          foreach ($label in $PR_LABEL_LIST) {
              # Check if the current label is a valid release type
              if ($label -in $validReleaseTypes) {
                  $typeCount++
                  $foundReleaseType = $label
              }
              # Check if the current label is a valid SDK type
              if ($label -in $validSdkTypes) {
                  $sdkTypeCount++
              }
          }

          # Validate that exactly one release type was found
          if ($typeCount -eq 1) {
              Write-Host "Release Type set to: $foundReleaseType"
              echo "RELEASE_TYPE=$foundReleaseType" >> $env:GITHUB_OUTPUT
          } else {
              throw "Error: Expected exactly one release type label (major, minor, patch, manual), but found $typeCount."
          }

          # Validate that only one SDK type was found
          if ($sdkTypeCount -gt 1) {
              throw "Error: Expected only one SDK type label (v1, v2, DirectoryInsights), but found $sdkTypeCount."
          }

          # --- Set Module Environment Variables ---
          if ('v1' -in $PR_LABEL_LIST) {
            Write-Host "Module label 'v1' found"
            echo "v1=true" >> $env:GITHUB_OUTPUT
          }
          if ('v2' -in $PR_LABEL_LIST) {
            Write-Host "Module label 'v2' found"
            echo "v2=true" >> $env:GITHUB_OUTPUT
          }
          if ('DirectoryInsights' -in $PR_LABEL_LIST) {
            Write-Host "Module label 'DirectoryInsights' found"
            echo "directoryinsights=true" >> $env:GITHUB_OUTPUT
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # =================================================================
  # == DRAFT GITHUB RELEASE JOBS
  # =================================================================

  Draft-Release-V1:
    needs: ['Check-PR-Labels']
    if: needs.Check-PR-Labels.outputs.V1 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Zip SDK Directory
        run: |
          cd ${{ github.workspace }}/SDKs/PowerShell/JumpCloud.SDK.V1/
          zip -r ${{ github.workspace }}/SDKs/PowerShell/JumpCloud.SDK.V1.zip ./*
      - name: Build and Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SDK_NAME="JumpCloud.SDK.V1"
          MODULE_CAPTURE=$(grep -Po "ModuleVersion = '(\d+\.\d+\.\d+)'" "${{ github.workspace }}/SDKs/PowerShell/${SDK_NAME}/${SDK_NAME}.psd1")
          VERSION=$(echo "$MODULE_CAPTURE" | grep -Po "(\d+\.\d+\.\d+)")
          TITLE="${SDK_NAME}-${VERSION}"
          TAG="${SDK_NAME}-${VERSION}"
          CHANGELOG=$(cat "${{ github.workspace }}/${SDK_NAME}.md" | awk "/^## ${SDK_NAME}-${VERSION}/{f=1; next} /^## ${SDK_NAME}-[0-9]+.[0-9]+.[0-9]+/{f=0} f")
          gh release create "$TAG" --title "$TITLE" --notes "$CHANGELOG" --draft "${{ github.workspace }}/SDKs/PowerShell/${SDK_NAME}.zip"

  Draft-Release-V2:
    needs: ['Check-PR-Labels']
    if: needs.Check-PR-Labels.outputs.V2 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Zip SDK Directory
        run: |
          cd ${{ github.workspace }}/SDKs/PowerShell/JumpCloud.SDK.V2/
          zip -r ${{ github.workspace }}/SDKs/PowerShell/JumpCloud.SDK.V2.zip ./*
      - name: Build and Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SDK_NAME="JumpCloud.SDK.V2"
          MODULE_CAPTURE=$(grep -Po "ModuleVersion = '(\d+\.\d+\.\d+)'" "${{ github.workspace }}/SDKs/PowerShell/${SDK_NAME}/${SDK_NAME}.psd1")
          VERSION=$(echo "$MODULE_CAPTURE" | grep -Po "(\d+\.\d+\.\d+)")
          TITLE="${SDK_NAME}-${VERSION}"
          TAG="${SDK_NAME}-${VERSION}"
          CHANGELOG=$(cat "${{ github.workspace }}/${SDK_NAME}.md" | awk "/^## ${SDK_NAME}-${VERSION}/{f=1; next} /^## ${SDK_NAME}-[0-9]+.[0-9]+.[0-9]+/{f=0} f")
          gh release create "$TAG" --title "$TITLE" --notes "$CHANGELOG" --draft "${{ github.workspace }}/SDKs/PowerShell/${SDK_NAME}.zip"

  Draft-Release-DI:
    needs: ['Check-PR-Labels']
    if: needs.Check-PR-Labels.outputs.DIRECTORYINSIGHTS == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: Zip SDK Directory
        run: |
          cd ${{ github.workspace }}/SDKs/PowerShell/JumpCloud.SDK.DirectoryInsights/
          zip -r ${{ github.workspace }}/SDKs/PowerShell/JumpCloud.SDK.DirectoryInsights.zip ./*
      - name: Build and Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SDK_NAME="JumpCloud.SDK.DirectoryInsights"
          MODULE_CAPTURE=$(grep -Po "ModuleVersion = '(\d+\.\d+\.\d+)'" "${{ github.workspace }}/SDKs/PowerShell/${SDK_NAME}/${SDK_NAME}.psd1")
          VERSION=$(echo "$MODULE_CAPTURE" | grep -Po "(\d+\.\d+\.\d+)")
          TITLE="${SDK_NAME}-${VERSION}"
          TAG="${SDK_NAME}-${VERSION}"
          CHANGELOG=$(cat "${{ github.workspace }}/${SDK_NAME}.md" | awk "/^## ${SDK_NAME}-${VERSION}/{f=1; next} /^## ${SDK_NAME}-[0-g]+.[0-9]+.[0-9]+/{f=0} f")
          gh release create "$TAG" --title "$TITLE" --notes "$CHANGELOG" --draft "${{ github.workspace }}/SDKs/PowerShell/${SDK_NAME}.zip"

  # =================================================================
  # == MANUAL APPROVAL GATE
  # =================================================================

  Manual-Approval-Release:
    needs: [Draft-Release-V1, Draft-Release-V2, Draft-Release-DI]
    if: always() && (needs.Draft-Release-V1.result == 'success' || needs.Draft-Release-V2.result == 'success' || needs.Draft-Release-DI.result == 'success')
    environment: PublishToPSGallery
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval for Release
        run: echo "Awaiting approval from required reviewers before continuing to publish."

  # =================================================================
  # == DEPLOY NUPKG JOBS
  # =================================================================

  Deploy-V1:
    needs: [Draft-Release-V1, Manual-Approval-Release]
    if: always() && needs.Draft-Release-V1.result == 'success' && needs.Manual-Approval-Release.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download SDK Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WF_NAME="jcapi-powershell-ci.yml"
          SDK_NAME="JumpCloud.SDK.V1"
          ARTIFACT_NAME="build-$SDK_NAME"
          RUN_ID=`gh run --repo ${{ github.repository }} list --workflow ${WF_NAME} --branch ${{ github.head_ref }} --json databaseId --jq .[0].databaseId`
          gh run --repo ${{ github.repository }} download ${RUN_ID} -n ${ARTIFACT_NAME}
          # List the artifiact directory/files
          ls -lR
          unzip "$SDK_NAME.zip"
      - name: Publish SDK to PSGallery
        shell: pwsh
        env:
          NuGetApiKey: ${{ secrets.NUGETAPIKEY }}
        run: |
          $SDK_NAME = "JumpCloud.SDK.V1"
          dotnet nuget add source "https://www.powershellgallery.com/api/v2/package" --name PSGallery
          $nupkgPath = (Get-ChildItem -Path "./$SDK_NAME/bin/nupkg/$($SDK_NAME)*.nupkg").FullName
          Write-Host "Nupkg Path: $nupkgPath"
          # TODO: Uncomment the following lines when ready to deploy
          # if (-not (Test-Path $nupkgPath)) { throw "Nupkg file not found for $SDK_NAME." }
          # dotnet nuget push $nupkgPath --source PSGallery --api-key $env:NuGetApiKey

  Deploy-V2:
    needs: [Draft-Release-V2, Manual-Approval-Release]
    if: always() && needs.Draft-Release-V2.result == 'success' && needs.Manual-Approval-Release.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download SDK Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WF_NAME="jcapi-powershell-ci.yml"
          SDK_NAME="JumpCloud.SDK.V2"
          ARTIFACT_NAME="build-$SDK_NAME"
          RUN_ID=`gh run --repo ${{ github.repository }} list --workflow ${WF_NAME} --branch ${{ github.head_ref }} --json databaseId --jq .[0].databaseId`
          gh run --repo ${{ github.repository }} download ${RUN_ID} -n ${ARTIFACT_NAME}
          # List the artifiact directory/files
          ls -lR
          unzip "$SDK_NAME.zip"
      - name: Publish SDK to PSGallery
        shell: pwsh
        env:
          NuGetApiKey: ${{ secrets.NUGETAPIKEY }}
        run: |
          $SDK_NAME = "JumpCloud.SDK.V2"
          dotnet nuget add source "https://www.powershellgallery.com/api/v2/package" --name PSGallery
          $nupkgPath = (Get-ChildItem -Path "./$SDK_NAME/bin/nupkg/$($SDK_NAME)*.nupkg").FullName
          Write-Host "Nupkg Path: $nupkgPath"
          # TODO: Uncomment the following lines when ready to deploy
          # if (-not (Test-Path $nupkgPath)) { throw "Nupkg file not found for $SDK_NAME." }
          # dotnet nuget push $nupkgPath --source PSGallery --api-key $env:NuGetApiKey

  Deploy-DI:
    needs: [Draft-Release-DI, Manual-Approval-Release]
    if: always() && needs.Draft-Release-DI.result == 'success' && needs.Manual-Approval-Release.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download SDK Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WF_NAME="jcapi-powershell-ci.yml"
          SDK_NAME="JumpCloud.SDK.DirectoryInsights"
          ARTIFACT_NAME="build-$SDK_NAME"
          RUN_ID=`gh run --repo ${{ github.repository }} list --workflow ${WF_NAME} --branch ${{ github.head_ref }} --json databaseId --jq .[0].databaseId`
          gh run --repo ${{ github.repository }} download ${RUN_ID} -n ${ARTIFACT_NAME}
          # List the artifiact directory/files
          ls -lR
          unzip "$SDK_NAME.zip"
      - name: Publish SDK to PSGallery
        shell: pwsh
        env:
          NuGetApiKey: ${{ secrets.NUGETAPIKEY }}
        run: |
          $SDK_NAME = "JumpCloud.SDK.DirectoryInsights"
          dotnet nuget add source "https://www.powershellgallery.com/api/v2/package" --name PSGallery
          $nupkgPath = (Get-ChildItem -Path "./$SDK_NAME/bin/nupkg/$($SDK_NAME)*.nupkg").FullName
          Write-Host "Nupkg Path: $nupkgPath"
          # TODO: Uncomment the following lines when ready to deploy
          # if (-not (Test-Path $nupkgPath)) { throw "Nupkg file not found for $SDK_NAME." }
          # dotnet nuget push $nupkgPath --source PSGallery --api-key $env:NuGetApiKey